[Vulkano-1441] Adding the possibility to generate mipmaps at image creation
vulkano-rs/vulkano pull request #1451
Opened 2020-12-06 00:10 UTC by qnope

I am a rust beginner, so, if there is anything to change, tell me.

To do so, I created a SubImage that implements the ImageAccess trait
This SubImage will decorate an ImageAccess image and will represent
one or more mip level / array layer level

Originally, I wanted to modify both `ImmutableImage` and `InitializationImmutableImage` in order to have the possibility to manage the mip levels / array layer levels directly on them, but I don't know vulkano enough to be able to do such a thing...

Maybe, it could be nice to have the `SubImage` type in another file, since it could be used by storage image also.

Hope it can help :)

2020-12-08 22:58 UTC, Eliah-Lakhin requested changes
I left a few comments.

Also, mind you add a few tests: for multi-mipmap cases and for single-mipmap cases both to cover the old and new implementations?

Thank you.

2020-12-08 22:58 UTC, Eliah-Lakhin commented on CHANGELOG_VULKANO.md
> +- **Breaking** The `ImmutableImage::from_iter` and `ImmutableImage::from_buffer` can build Mipmaps
Please sync with the latest `master`.

2020-12-08 22:58 UTC, Eliah-Lakhin commented on vulkano/src/image/immutable.rs
> +pub struct SubImage<Img> {
A new public API object probably needs some rustdoc description.

2020-12-08 22:58 UTC, Eliah-Lakhin commented on vulkano/src/image/immutable.rs
> +        let init = SubImage::new(
What would happen if the end-user use `uninitialized`'s initializer and the `SubImage` objects both?

2020-12-08 22:58 UTC, Eliah-Lakhin commented on vulkano/src/image/immutable.rs
> +            transfer_source: true,
Internally I would separate implementation into two cases: when the user specifies more than One mipmaps(current implementation) and specifies just a single mipmap(previous implementation) to avoid extra steps for a single-mipmap case which might be a common use case.

2020-12-08 22:58 UTC, Eliah-Lakhin commented on vulkano/src/image/immutable.rs
> +                unreachable!();
These two lines could be combined together `unreachable!("{:?}", e)`

2020-12-09 19:34 UTC, qnope commented
I will do the modification in the following days :)
Thanks !

2020-12-14 12:39 UTC, qnope commented on vulkano/src/image/immutable.rs
> +        let init = SubImage::new(
I don't know why I deleted it, it is fixed

2020-12-14 12:39 UTC, qnope commented on vulkano/src/image/immutable.rs
> +pub struct SubImage<Img> {
I hope what I did is correct about the doc

2020-12-14 12:43 UTC, qnope commented
I hope I have fixed all the comments you made.
Regarding the test, you mean adding an example that uses mipmaps?

2020-12-15 19:57 UTC, Eliah-Lakhin commented
@qnope Thank you very much for the fixes! The code looks good, I would merge it.

How do you think do we need unit tests before I merge? Maybe without the actual mipmap content checking, but just checking if image creation process with and without mipmaps passes without failures. That would help for future maintainability to verify if we have regressions.

2020-12-15 20:06 UTC, qnope commented
I am going to try to write some little unit tests before the weekend :).
I'll let you know when it will be mergeable :)

2020-12-18 19:44 UTC, qnope commented
I have written very very tiny tests... (not really proud ahaha) But I hope it'll be enough :)
Thanks

2020-12-19 03:08 UTC, merged

2020-12-19 03:12 UTC, Eliah-Lakhin commented
@qnope PR merged. Thank you very much for your help to the project and the community! :)

2021-07-13 16:18 UTC, Rua commented
Looking back at this code now, @qnope I wonder if you could explain something to me? You added two new methods to the `ImageAccess` trait, namely `current_miplevels_access` and `current_layer_levels_access`. These are supposed to return the range of mipmaps and array layers that an `ImageAccess` represents, relative to the "full" image. However, the `ImageInner` type, which is also returned from the `ImageAccess` trait, seems to contain these same values, except that your new type `SubImage` doesn't correctly set them. Was this an oversight on your part? Please let me know what the intent was here, as I'm working on a PR that changes this.

2021-07-14 08:53 UTC, qnope commented
Hello @Rua 

When I did the fix, I was (and actually I am still) a novice both in rust and in vulkano rs.
I did not have knowledge that the  `ImageInner` type existed. So it is highly likely that there exists a much better way for adding mipmaps and I encourage you to change it to make things better :).

When your PR is ready, please quote me to see your changes :)

2021-07-14 08:57 UTC, Rua commented
Thank you for clarifying!