improved image layout transitions
vulkano-rs/vulkano pull request #1588
Opened 2021-05-20 20:14 UTC by Timbals

I ran into the same problems that issue #1578 described when using [RenderDoc][renderdoc] to replay Vulkan commands and traced it down to `vulkano` inserting image memory barriers at the beginning of the renderpass that transitionend my textures from `UNDEFINED` to `VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL`. This caused [RenderDoc][renderdoc] to fill the texture with [a pattern for recognising discarded resources][renderdoc-issue].

They do this because according to [the vulkan specification][spec-undefined-discard]:
> Layout transitions always apply to a particular image subresource range, and specify both an old layout and new layout. [...] If the old layout is VK_IMAGE_LAYOUT_UNDEFINED, **the contents of that range may be discarded**.

Although this doesn't actually cause issues on my machine (NVIDIA GPU) this should probably still be fixed for correctness and to remove unneccessary image memory barriers.
I removed the default implementation of the `layout_initialized` and `is_layout_initialized` functions of the `ImageAccess` trait and implemented these for all remaining `vulkano` types that implement `ImageAccess`.

This is a breaking change for anyone that currently implements the `ImageAccess` trait.

fixes #1578
fixes #1595

Entries for Vulkano changelog:
- **Breaking** the first `CommandBuffer` that uses images will now initialize their layout which means the execution of the first command buffer that uses an image should be finished before recording more command buffers that use the image
- **Breaking** the `ImageAccess` trait now requires the implementation of the `layout_initialized()` and `current_layout()` functions, removed the  `layout_initialized()`, `initial_layout_requirement()` and `forced_undefined_initial_layout()` functions and changed the `unlock()` function to always receive the image layout that a command buffer transitioned to
- **Breaking** the `check_image_access()` function should no longer ignore `Undefined` layouts
- fixed incorrect layout transitions that caused issues when using RenderDoc
- implemented `is_layout_initialized()`, `try_gpu_lock()` and `unlock()` correctly for all image access types

[renderdoc]: https://renderdoc.org/
[renderdoc-issue]: https://github.com/baldurk/renderdoc/issues/284
[spec-undefined-discard]: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#synchronization-image-layout-transitions

2021-05-21 07:32 UTC, Rua commented
Thank you for taking the time to fix this!

I've been pondering this problem myself, and noticed that there is a subtle bug that can happen with the current code. `layout_initialized` is called when _recording_ a command buffer, which is fine as long as you submit the command buffers in the same order that you record them. But does this still work if you submit the command buffers in a different order, or worse, if you drop the buffer that does the initialization without submitting it altogether? This isn't criticism against your PR btw, it's just something that still needs considering for a future fix.

2021-05-21 11:21 UTC, Timbals commented
I looked through the code and didn't find any easy way to fix the bug.

What do you think about removing the call to `layout_initialized` for now?
That would mean images are only marked as initialized in `unlock` which is after the layout transition has been completed. It would still cause other command buffers that get recorded before the `unlock` to insert incorrect image memory barriers (which they currently always do anyway without this PR).

Additionally `try_gpu_lock` could be changed to take an `Option<ImageLayout>` where the `None` value indicates that the caller doesn't care about the layout and `Some(Undefined)` indicates the caller expects the image to still be in an undefined layout. That would enable safe tracking of the image layout but would probably require some effort to change the command buffer builder implementation and is probably out of scope for this PR.

Removing the call to `layout_initialized` should be enough for this PR.

2021-05-23 16:49 UTC, Eliah-Lakhin commented
@Timbals Thank you for your contribution.

Unfortunately, I can't fully wrap my head around this issue as I'm not fully understand synchronization mechanisms too, so I would left it for your decision(@Timbals and @Rua) and will test just the final result. Please let me know when it's ready for the final review. Thanks!

2021-05-26 06:37 UTC, AustinJ235 commented
Just some thoughts. Ran into to this in my project.

So what I can manage to sort out is that there are 3 layouts that an image could be in, VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_PREINITIALIZED, and VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL; talking just color ones that is. undefined and preinitialized sound to me like they would be write only in this state and it is only where we'd be reading that layout would truly matter. Could be wrong here though. Would it be possible to remove layout checks where we'd be writing? Although undefined hints that it doesn't have a layout is this important? Then make it so where the image/resource is being read from that it needs to be in an optimal state?

2021-05-26 08:36 UTC, Rua commented
`VK_IMAGE_LAYOUT_PREINITIALIZED` only works for linear tiling, where layouts don't matter. And I don't believe any of Vulkano uses it currently.

`VK_IMAGE_LAYOUT_UNDEFINED` indeed means that the image can only be written (following a layout transition to something sensible). But more specifically, it means that the image is considered garbage, and any part of the image that is to be read from must have been written first. In theory, you can write to part of an image, leaving the rest still uninitialised. Then read from that part and write to another part. I believe this technique can be used for generating mipmaps: you write the largest mipmap first, then read from it in order to generate the next, then read from that in order to generate the next, etc.

Moreover, it is in theory possible to _transition_ only part of an image. That is, different parts can have different layouts. I don't know how Vulkano would deal with such a scenario, since it would essentially have to keep track of which parts of an image are initialised with data and which are still garbage. That would be really complex to handle. It would be simpler if Vulkano enforced that the entire image must have a single layout, and that all of it must be initialised at once.

Vulkano doesn't currently have any way to detect/enforce initialisation with data though. `SyncCommandBufferBuilder` inserts a layout transition from `VK_IMAGE_LAYOUT_UNDEFINED` at the start of the command buffer, but it doesn't check at all if the first use is a read or a write, nor if that write covers the whole image. In the case of writes by a shader to a storage image it may be impossible to detect this, too. A shader could read/write to a storage image at will, and Vulkano has no hope of enforcing that the shader writes to every pixel, nor that it doesn't read from uninitialised pixels.

2021-05-26 09:39 UTC, AustinJ235 commented
Another thing would be, is it worth the extra runtime checks for the small amount of safely? I mean the user is going to know if they are reading garbage or not. I don't think anything bad happens from reading garbage data.

2021-05-26 09:41 UTC, Rua commented
It is technically undefined behaviour, which is very evil in the world of Rust. But I don't know if UB on the GPU has the same kinds of consequences as UB on the CPU.

2021-05-26 09:47 UTC, AustinJ235 commented
I think if we do implement any sort of checks that it should be once the image has any sort of write access it is assumed that it is read ready. That'd probably be enough to catch most common errors people make, and it wouldn't have that much overhead I wouldn't think.

2021-05-26 09:49 UTC, AustinJ235 commented
Although we'd have to check if for example an AttachmentImage is transient or not, because in that case the gpu doesn't care what is stored before or after the renderpass.

2021-05-31 20:33 UTC, Timbals commented
@Eliah-Lakhin ready for review

2021-06-07 14:18 UTC, Eliah-Lakhin commented
@Timbals I merged the recent `master` onto your branch(locally) and triangle example is failing with the following error:

```
Using device: Intel(R) HD Graphics 630 (KBL GT2) (type: IntegratedGpu)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AccessError { error: ImageNotInitialized { requested: Undefined }, command_name: "vkCmdBeginRenderPass", command_param: "attachment 0", command_offset: 0 }', examples/src/bin/triangle.rs:489:22
```

Same with AMD, and some other examples.

2021-06-07 14:21 UTC, Eliah-Lakhin requested changes
Please see my comment above.

2021-06-07 14:22 UTC, Eliah-Lakhin commented
@Timbals fyi, I set your PR on priority. So, once all related issues will be fixed I will proceed with merging as soon as possible. I would like to include this fix in the upcoming release. Thank you.

2021-06-07 15:23 UTC, Timbals commented
I fixed the immediate issue.

There is still an issue with the `teapot` example (and probably others as well).
The command buffer for the first frame contains image layout transitions from `UNDEFINED` to the correct layouts. When the command buffer for the second frame gets recorded it also inserts transitions from `UNDEFINED` to the correct layouts because the first command buffer is still in flight and the layouts have not been changed yet. These additional transitions cause an error at submission time.

2021-06-07 15:32 UTC, Eliah-Lakhin commented
@Timbals Thank you for the fix. Would it be possible to provide fixes for other examples too? We are using these examples as a form of least manual tests to check if no regressions introduced.

2021-06-07 18:41 UTC, Timbals commented
@Eliah-Lakhin I've added a workaround to all affected examples. I'm not sure what a better long-term solution would look like because Vulkano can't know in which order command buffers get submitted (or if at all) by the user.

2021-06-08 07:31 UTC, Rua commented
Perhaps there could be an `unsafe` command added to the command buffer builder, that manually adds the layout transition (presumably only from `Undefined` to the image's standard one). The constructors of the various image types can then use this command. That way, it is no longer necessary for the builder to try to autodetect the state of the image. It needs to be unsafe, because if you transition an image and then don't fill it with data, you read garbage. So the user of this command has to promise to fill the image with data before using it.

2021-06-13 16:36 UTC, Eliah-Lakhin commented
@Timbals, @Rua  Honestly speaking I don't like the current workaround. It's unclear for the user why they need to wait for the first submission. Moreover, it looks like this is a behavior that should normally be encapsulated somewhere inside Vulkano. Why can't we implement synchronization under the hood, e.g. in the gpu futures mechanism?

2021-06-13 16:39 UTC, Eliah-Lakhin commented
Or at least we can add more explicit method for gpu future to check for required transitions. Kind of `future.ensure_image_layout_transition()`. And it will be up to the user to put this method based on the program logic.

2021-06-13 20:01 UTC, Eliah-Lakhin commented
@AustinJ235 May I ask you to help me with this Pull Request review, please?

2021-06-13 23:57 UTC, AustinJ235 commented
@Eliah-Lakhin I am investigating a solution to this. I personally believe this pull request is the wrong approach. I think the user should have not have to think about transitioning the image.

2021-06-14 05:38 UTC, AustinJ235 commented
@Eliah-Lakhin Seems I was having another possibly unrelated issue. I think the issues outlined in https://github.com/vulkano-rs/vulkano/issues/1578 seem valid. But in this pull request the user is having to keep track of if something is initialized, I don't like that one bit. I think in that specific case my fix for the issue I was having would solve specific issue.

I think the methods `is_layout_initialized` & `layout_initialized` should be reviewed more. There might be an issue there with memory barriers in the aforementioned issue.

2021-06-14 10:59 UTC, Timbals commented
I also don't like the current solution.
A better approach would probably be to transition images to a layout when they are created and require all command buffers to transition any image resource back to its specified layout after use.
The downside would be that image creation would involve a command buffer submission and waiting on the resulting future.

2021-06-14 11:01 UTC, Rua commented
> A better approach would probably be to transition images to a layout when they are created and require all command buffers to transition any image resource back to its specified layout after use.
> The downside would be that image creation would involve a command buffer submission and waiting on the resulting future.

Isn't that exactly how all the current images already work?

2021-06-14 11:06 UTC, Timbals commented
@Rua as far as I know no image layouts are currently initialized at image creation and instead get re-initialized in every command buffer which may discard all contents of the image. The change from the current implementation would be to do the initialization once at image creation.

2021-06-14 11:13 UTC, Rua commented
Unless I'm missing something, when an image is created with data to initialise it, the constructor first creates a `CpuAccessibleBuffer` and directly writes the image data to it. Then it creates a command buffer and adds a copy command to copy from the CPU buffer to the GPU image. This command buffer then gets executed on the queue, and its future is returned from the constructor.

The constructor itself doesn't do any image transition, but the command buffer that is being created here is supposed to recognise automatically that the image is uninitialised, and add the transition itself. It's this detection that's going wrong currently. In [this comment](https://github.com/vulkano-rs/vulkano/pull/1588#issuecomment-856530332) above, I proposed an alternative solution: instead of the command buffer trying to figure out when to add the transition, the image constructor does it itself, via a new command on the command buffer builder.

2021-06-14 15:38 UTC, Timbals commented
I implemented the solution that makes images initialize their layout when they are created.
That means the user doesn't have to worry about transitions anymore and the only change in the examples is that creating images now required passing in a `Queue` that will be used to execute the transition.

2021-06-15 14:35 UTC, Rua commented on vulkano/src/command_buffer/auto.rs
> +    /// The layout of the image must not have been transitioned to `image.layout()` before.
This is actually not unsafe. When you transition from `Undefined`, the previous contents is ignored, so there's no problem. What the user _should_ do here, though, is make sure that the image is filled with valid contents before it's read.

2021-06-20 05:46 UTC, Eliah-Lakhin commented
@Timbals I proceeded with merging of #1608 from @AustinJ235 . I hope it would help resolving the issue at least in form of a workaround.

I would like to ask you and @Rua if it resolving the original issue too, and if you think that Austin's solution needs further investigations and improvements.

2021-07-04 10:32 UTC, Rua commented
@Timbals are you still working on this?

2021-07-19 15:43 UTC, Timbals commented
I don't have the time to work on this any more, so I'm closing the Pull Request.

2021-07-19 15:43 UTC, closed without merging