Add checks for `khr_portability_subset`
vulkano-rs/vulkano pull request #2044
Opened 2022-10-23 07:32 UTC by Rua

Changelog:
```markdown
### Bugs fixed
- Validation checks for `khr_portability_subset` devices.
````

This adds the missing validation checks for devices that expose the `khr_portability_subset` extension. This concerns MacOS and iOS devices, which do not fully conform to the Vulkan spec, and therefore do not support all the features that a conformant Vulkan implementation is expected to support. For such devices, certain features must be enabled on the device (if they are available) in order to use them.

2022-10-23 22:53 UTC, AustinJ235 requested changes
Aside from the typo, looks good.

2022-10-23 22:53 UTC, AustinJ235 commented on vulkano/src/sampler/mod.rs
> +                    features: &["sampker_mip_lod_bias"],
``sampker`` :thinking:

2022-10-24 07:08 UTC, Rua commented on vulkano/src/sampler/mod.rs
> +                    features: &["sampker_mip_lod_bias"],
Oops, thanks! Fixed now.

2022-10-24 07:33 UTC, AustinJ235 approved these changes

2022-10-24 07:33 UTC, merged